//! Host-side key event model and classification.
//!
//! The dispatcher works on `KeyEvent`s produced by the platform keyboard hook
//! (WH_KEYBOARD_LL on Windows). All classification rules live here so the
//! dispatch logic stays portable and testable.

/// What kind of key press a `KeyEvent` represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyKind {
    /// A printable character (already resolved for the active layout/shift
    /// state — e.g. `a`, `A`, `1`, `!`).
    Char(char),
    /// Backspace.
    Backspace,
    /// A word-terminating key that was not reported as a `Char`
    /// (Enter, Tab, Escape).
    Break,
    /// Navigation/editing keys that move the caret or change selection
    /// (arrows, Home, End, PageUp/Down, Delete).
    Navigation,
    /// A non-printable key we don't care about (F-keys, OEM keys, etc.).
    Other,
}

/// A normalized key press as seen by the dispatcher.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyEvent {
    pub kind: KeyKind,
    /// Ctrl held (either side).
    pub ctrl: bool,
    /// Alt held (either side).
    pub alt: bool,
    /// Whether this event was generated by another input source and must be
    /// ignored (e.g. our own SendInput injections echoing back).
    pub injected: bool,
}

impl KeyEvent {
    pub fn char(ch: char) -> Self {
        Self {
            kind: KeyKind::Char(ch),
            ctrl: false,
            alt: false,
            injected: false,
        }
    }

    pub fn backspace() -> Self {
        Self {
            kind: KeyKind::Backspace,
            ..Self::char('\0')
        }
    }

    /// True when this key ends a word boundary and should commit the
    /// composing buffer (space, punctuation, Enter/Tab, etc.).
    pub fn is_word_break(&self) -> bool {
        match self.kind {
            KeyKind::Break => true,
            KeyKind::Char(c) => is_word_break_char(c),
            _ => false,
        }
    }
}

/// ASCII characters that terminate a Vietnamese word on the engine side.
/// Mirrors uvie-mac's break-key table: whitespace and all punctuation that
/// can never be part of a Telex/VNI sequence.
pub fn is_word_break_char(c: char) -> bool {
    matches!(
        c,
        ' ' | '\t'
            | '\n'
            | '\r'
            | '.'
            | ','
            | ';'
            | ':'
            | '?'
            | '!'
            | '\''
            | '"'
            | '('
            | ')'
            | '['
            | ']'
            | '{'
            | '}'
            | '<'
            | '>'
            | '/'
            | '\\'
            | '|'
            | '-'
            | '_'
            | '='
            | '+'
            | '*'
            | '&'
            | '^'
            | '%'
            | '$'
            | '#'
            | '@'
            | '~'
            | '`'
    )
}

/// Digits are feedable keys in VNI (1-9 are tone keys) but plain text in
/// Telex; the engine handles both — the dispatcher always feeds them.
pub fn is_feedable_ascii(c: char) -> bool {
    c.is_ascii() && !c.is_ascii_control()
}
